import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_elevated_button.dart';import 'bloc/profile_details_bloc.dart';import 'models/profile_details_model.dart';import 'models/profiledetails_item_model.dart';import 'widgets/profiledetails_item_widget.dart';class ProfileDetailsScreen extends StatelessWidget {const ProfileDetailsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ProfileDetailsBloc>(create: (context) => ProfileDetailsBloc(ProfileDetailsState(profileDetailsModelObj: ProfileDetailsModel()))..add(ProfileDetailsInitialEvent()), child: ProfileDetailsScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 30.v), child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgEllipse5, height: 250.adaptSize, width: 250.adaptSize, radius: BorderRadius.circular(125.h)), SizedBox(height: 26.v), Text("lbl_jenny_wilson".tr, style: theme.textTheme.headlineLarge), SizedBox(height: 19.v), CustomElevatedButton(height: 45.v, width: 101.h, text: "lbl_follow".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL22, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700_1, onPressed: () {onTapFollow(context);}), SizedBox(height: 21.v), Divider(), SizedBox(height: 20.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [GestureDetector(onTap: () {onTapAutoLayoutVertical(context);}, child: Padding(padding: EdgeInsets.only(bottom: 2.v), child: Column(children: [Text("lbl_9_489".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 8.v), Text("lbl_followers".tr, style: CustomTextStyles.titleMediumGray70001Medium)]))), Padding(padding: EdgeInsets.only(left: 70.h), child: Column(children: [Text("lbl_2_475".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 10.v), Text("lbl_following".tr, style: CustomTextStyles.titleMediumGray70001Medium)]))]), SizedBox(height: 20.v), Divider(), SizedBox(height: 15.v), _buildPlaylists(context), SizedBox(height: 13.v), _buildProfileDetails(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 11.v)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 11.v))]); } 
/// Section Widget
Widget _buildPlaylists(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_playlists".tr, style: theme.textTheme.headlineSmall), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 6.v), child: Text("lbl_see_all".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer16))]); } 
/// Section Widget
Widget _buildProfileDetails(BuildContext context) { return SizedBox(height: 248.v, child: BlocSelector<ProfileDetailsBloc, ProfileDetailsState, ProfileDetailsModel?>(selector: (state) => state.profileDetailsModelObj, builder: (context, profileDetailsModelObj) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: profileDetailsModelObj?.profiledetailsItemList.length ?? 0, itemBuilder: (context, index) {ProfiledetailsItemModel model = profileDetailsModelObj?.profiledetailsItemList[index] ?? ProfiledetailsItemModel(); return ProfiledetailsItemWidget(model);});})); } 
/// Navigates to the songPlayScreen when the action is triggered.
onTapFollow(BuildContext context) { NavigatorService.pushNamed(AppRoutes.songPlayScreen, ); } 

onTapAutoLayoutVertical(BuildContext context) { // TODO: implement Actions
 } 
 }
