import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_title.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'bloc/popular_artists_bloc.dart';import 'models/popular_artists_model.dart';import 'models/popularartists_item_model.dart';import 'widgets/popularartists_item_widget.dart';class PopularArtistsScreen extends StatelessWidget {const PopularArtistsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<PopularArtistsBloc>(create: (context) => PopularArtistsBloc(PopularArtistsState(popularArtistsModelObj: PopularArtistsModel()))..add(PopularArtistsInitialEvent()), child: PopularArtistsScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 27.v), child: _buildPopularArtists(context))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 52.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 13.v)), title: AppbarTitle(text: "lbl_popular_artists".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.fromLTRB(24.h, 11.v, 24.h, 13.v))]); } 
/// Section Widget
Widget _buildPopularArtists(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: BlocSelector<PopularArtistsBloc, PopularArtistsState, PopularArtistsModel?>(selector: (state) => state.popularArtistsModelObj, builder: (context, popularArtistsModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 220.v, crossAxisCount: 2, mainAxisSpacing: 12.h, crossAxisSpacing: 12.h), physics: NeverScrollableScrollPhysics(), itemCount: popularArtistsModelObj?.popularartistsItemList.length ?? 0, itemBuilder: (context, index) {PopularartistsItemModel model = popularArtistsModelObj?.popularartistsItemList[index] ?? PopularartistsItemModel(); return PopularartistsItemWidget(model);});})); } 
 }
