import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_title.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_radio_button.dart';import 'bloc/language_bloc.dart';import 'models/language_model.dart';class LanguageScreen extends StatelessWidget {const LanguageScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<LanguageBloc>(create: (context) => LanguageBloc(LanguageState(languageModelObj: LanguageModel()))..add(LanguageInitialEvent()), child: LanguageScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 28.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_suggested".tr, style: theme.textTheme.titleLarge), SizedBox(height: 22.v), _buildSuggestedRadioGroup(context), SizedBox(height: 30.v), Divider(), SizedBox(height: 30.v), Text("lbl_others".tr, style: theme.textTheme.titleLarge), SizedBox(height: 23.v), _buildOthersRadioGroup(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 14.v)), title: AppbarTitle(text: "lbl_language".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildSuggestedRadioGroup(BuildContext context) { return BlocBuilder<LanguageBloc, LanguageState>(builder: (context, state) {return state.languageModelObj!.radioList.isNotEmpty ? Column(children: [CustomRadioButton(width: 380.h, text: "lbl_english_us".tr, value: state.languageModelObj?.radioList[0] ?? "", groupValue: state.suggestedRadioGroup, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButtonEvent(value: value));}), Padding(padding: EdgeInsets.only(top: 20.v), child: CustomRadioButton(width: 380.h, text: "lbl_english_uk".tr, value: state.languageModelObj?.radioList[1] ?? "", groupValue: state.suggestedRadioGroup, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButtonEvent(value: value));}))]) : Container();}); } 
/// Section Widget
Widget _buildOthersRadioGroup(BuildContext context) { return BlocBuilder<LanguageBloc, LanguageState>(builder: (context, state) {return state.languageModelObj!.radioList1.isNotEmpty ? Column(children: [CustomRadioButton(width: 380.h, text: "lbl_mandarin".tr, value: state.languageModelObj?.radioList1[0] ?? "", groupValue: state.othersRadioGroup, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButton1Event(value: value));}), Padding(padding: EdgeInsets.only(top: 20.v), child: CustomRadioButton(width: 380.h, text: "lbl_hindi".tr, value: state.languageModelObj?.radioList1[1] ?? "", groupValue: state.othersRadioGroup, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButton1Event(value: value));})), Padding(padding: EdgeInsets.only(top: 21.v), child: CustomRadioButton(width: 380.h, text: "lbl_spanish".tr, value: state.languageModelObj?.radioList1[2] ?? "", groupValue: state.othersRadioGroup, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButton1Event(value: value));})), Padding(padding: EdgeInsets.only(top: 17.v), child: CustomRadioButton(width: 380.h, text: "lbl_french".tr, value: state.languageModelObj?.radioList1[3] ?? "", groupValue: state.othersRadioGroup, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButton1Event(value: value));})), Padding(padding: EdgeInsets.only(top: 20.v), child: CustomRadioButton(width: 380.h, text: "lbl_arabic".tr, value: state.languageModelObj?.radioList1[4] ?? "", groupValue: state.othersRadioGroup, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButton1Event(value: value));})), Padding(padding: EdgeInsets.only(top: 21.v), child: CustomRadioButton(width: 380.h, text: "lbl_bengali".tr, value: state.languageModelObj?.radioList1[5] ?? "", groupValue: state.othersRadioGroup, isRightCheck: true, onChange: (value) {context.read<LanguageBloc>().add(ChangeRadioButton1Event(value: value));}))]) : Container();}); } 
 }
