import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'bloc/top_albums_global_bloc.dart';import 'models/top_albums_global_model.dart';import 'models/topalbumsgloballist_item_model.dart';import 'widgets/topalbumsgloballist_item_widget.dart';class TopAlbumsGlobalScreen extends StatelessWidget {const TopAlbumsGlobalScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<TopAlbumsGlobalBloc>(create: (context) => TopAlbumsGlobalBloc(TopAlbumsGlobalState(topAlbumsGlobalModelObj: TopAlbumsGlobalModel()))..add(TopAlbumsGlobalInitialEvent()), child: TopAlbumsGlobalScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 30.v), child: Column(children: [_buildPriceStack(context), SizedBox(height: 18.v), Text("msg_top_albums_global2".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 12.v), Text("msg_the_most_played".tr, style: CustomTextStyles.titleMediumMedium), SizedBox(height: 14.v), Text("msg_by_hearme_12_24_2022".tr, style: CustomTextStyles.titleSmallGray70001), SizedBox(height: 23.v), Divider(), SizedBox(height: 23.v), _buildTopAlbumsGlobalList(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconlyLightOutlineArrow, margin: EdgeInsets.fromLTRB(24.h, 11.v, 376.h, 11.v), onTap: () {onTapImage(context);})); } 
/// Section Widget
Widget _buildPriceStack(BuildContext context) { return SizedBox(height: 184.v, width: 380.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImage184x380, height: 184.v, width: 380.h, radius: BorderRadius.circular(28.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: SizedBox(width: 98.h, child: Text("msg_top_albums_global".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.headlineSmallWhiteA700.copyWith(height: 1.20))))])); } 
/// Section Widget
Widget _buildTopAlbumsGlobalList(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 8.h), child: BlocSelector<TopAlbumsGlobalBloc, TopAlbumsGlobalState, TopAlbumsGlobalModel?>(selector: (state) => state.topAlbumsGlobalModelObj, builder: (context, topAlbumsGlobalModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: topAlbumsGlobalModelObj?.topalbumsgloballistItemList.length ?? 0, itemBuilder: (context, index) {TopalbumsgloballistItemModel model = topAlbumsGlobalModelObj?.topalbumsgloballistItemList[index] ?? TopalbumsgloballistItemModel(); return TopalbumsgloballistItemWidget(model, onTapSongCard: () {onTapSongCard(context);});});})); } 
/// Navigates to the songPlayScreen when the action is triggered.
onTapSongCard(BuildContext context) { NavigatorService.pushNamed(AppRoutes.songPlayScreen); } 

/// Navigates to the previous screen.
onTapImage(BuildContext context) { NavigatorService.goBack(); } 
 }
