import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_elevated_button.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_icon_button.dart';import 'bloc/artist_details_bloc.dart';import 'models/artist_details_model.dart';import 'models/artistdetails_item_model.dart';import 'widgets/artistdetails_item_widget.dart';class ArtistDetailsScreen extends StatelessWidget {const ArtistDetailsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ArtistDetailsBloc>(create: (context) => ArtistDetailsBloc(ArtistDetailsState(artistDetailsModelObj: ArtistDetailsModel()))..add(ArtistDetailsInitialEvent()), child: ArtistDetailsScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 30.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgEllipse250x250, height: 250.adaptSize, width: 250.adaptSize, radius: BorderRadius.circular(125.h)), SizedBox(height: 14.v), Text("lbl_ariana_grande".tr, style: theme.textTheme.headlineLarge), SizedBox(height: 15.v), Text("msg_55_278_829_monthly".tr, style: CustomTextStyles.titleMediumPrimaryMedium), SizedBox(height: 19.v), _buildAutoLayoutHorizontal(context), SizedBox(height: 24.v), Divider(), SizedBox(height: 24.v), _buildAutoLayoutHorizontal1(context), SizedBox(height: 21.v), _buildArtistDetails(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 11.v)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 11.v))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomElevatedButton(height: 45.v, width: 101.h, text: "lbl_follow".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL22, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700_1), CustomImageView(imagePath: ImageConstant.imgCategoriesMore, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v)), Spacer(), CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(3.h), child: CustomImageView(imagePath: ImageConstant.imgIconlyBoldPlay))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_popular_songs".tr, style: theme.textTheme.headlineSmall)), Padding(padding: EdgeInsets.only(bottom: 10.v), child: Text("lbl_see_all".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer16))]); } 
/// Section Widget
Widget _buildArtistDetails(BuildContext context) { return BlocSelector<ArtistDetailsBloc, ArtistDetailsState, ArtistDetailsModel?>(selector: (state) => state.artistDetailsModelObj, builder: (context, artistDetailsModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: artistDetailsModelObj?.artistdetailsItemList.length ?? 0, itemBuilder: (context, index) {ArtistdetailsItemModel model = artistDetailsModelObj?.artistdetailsItemList[index] ?? ArtistdetailsItemModel(); return ArtistdetailsItemWidget(model, onTapSongCard: () {onTapSongCard(context);});});}); } 
/// Navigates to the songPlayScreen when the action is triggered.
onTapSongCard(BuildContext context) { NavigatorService.pushNamed(AppRoutes.songPlayScreen); } 
 }
