import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_circleimage.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_subtitle.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_subtitle_one.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'bloc/home_bloc.dart';import 'models/artistsframe_item_model.dart';import 'models/home_model.dart';import 'models/topchartslist_item_model.dart';import 'models/trendingnowframe_item_model.dart';import 'widgets/artistsframe_item_widget.dart';import 'widgets/topchartslist_item_widget.dart';import 'widgets/trendingnowframe_item_widget.dart';class HomePage extends StatelessWidget {const HomePage({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<HomeBloc>(create: (context) => HomeBloc(HomeState(homeModelObj: HomeModel()))..add(HomeInitialEvent()), child: HomePage()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 27.v), child: Column(children: [Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(context, popularArtistsText: "lbl_trending_now".tr, seeAllText: "lbl_see_all".tr, onTapSeeAllText: () {onTapTxtSeeAllText(context);})), SizedBox(height: 13.v), _buildTrendingNowFrame(context), SizedBox(height: 32.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(context, popularArtistsText: "lbl_popular_artists".tr, seeAllText: "lbl_see_all".tr, onTapSeeAllText: () {onTapTxtSeeAllText1(context);})), SizedBox(height: 13.v), _buildArtistsFrame(context), SizedBox(height: 32.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(context, popularArtistsText: "lbl_top_charts".tr, seeAllText: "lbl_see_all".tr)), SizedBox(height: 13.v), _buildTopChartsList(context)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, leadingWidth: 72.h, leading: AppbarLeadingCircleimage(imagePath: ImageConstant.imgEllipse48x48, margin: EdgeInsets.only(left: 24.h, top: 2.v, bottom: 3.v)), title: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(children: [AppbarSubtitleOne(text: "lbl_good_morning".tr, margin: EdgeInsets.only(right: 18.h)), SizedBox(height: 6.v), AppbarSubtitle(text: "lbl_andrew_ainsley".tr)])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.only(left: 24.h, top: 12.v, right: 13.h)), AppbarTrailingImage(imagePath: ImageConstant.imgIconsGray90001, margin: EdgeInsets.only(left: 20.h, top: 12.v, right: 37.h))]); } 
/// Section Widget
Widget _buildTrendingNowFrame(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 220.v, child: BlocSelector<HomeBloc, HomeState, HomeModel?>(selector: (state) => state.homeModelObj, builder: (context, homeModelObj) {return ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: homeModelObj?.trendingnowframeItemList.length ?? 0, itemBuilder: (context, index) {TrendingnowframeItemModel model = homeModelObj?.trendingnowframeItemList[index] ?? TrendingnowframeItemModel(); return TrendingnowframeItemWidget(model);});}))); } 
/// Section Widget
Widget _buildArtistsFrame(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 193.v, child: BlocSelector<HomeBloc, HomeState, HomeModel?>(selector: (state) => state.homeModelObj, builder: (context, homeModelObj) {return ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: homeModelObj?.artistsframeItemList.length ?? 0, itemBuilder: (context, index) {ArtistsframeItemModel model = homeModelObj?.artistsframeItemList[index] ?? ArtistsframeItemModel(); return ArtistsframeItemWidget(model);});}))); } 
/// Section Widget
Widget _buildTopChartsList(BuildContext context) { return Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 24.h), child: BlocSelector<HomeBloc, HomeState, HomeModel?>(selector: (state) => state.homeModelObj, builder: (context, homeModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: homeModelObj?.topchartslistItemList.length ?? 0, itemBuilder: (context, index) {TopchartslistItemModel model = homeModelObj?.topchartslistItemList[index] ?? TopchartslistItemModel(); return TopchartslistItemWidget(model);});}))); } 
/// Common widget
Widget _buildPopularArtistsRow(BuildContext context, {required String popularArtistsText, required String seeAllText, Function? onTapSeeAllText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text(popularArtistsText, style: theme.textTheme.headlineSmall!.copyWith(color: appTheme.gray90001)), GestureDetector(onTap: () {onTapSeeAllText!.call();}, child: Padding(padding: EdgeInsets.only(bottom: 7.v), child: Text(seeAllText, style: CustomTextStyles.titleMediumOnPrimaryContainer16.copyWith(color: theme.colorScheme.onPrimaryContainer))))]); } 
/// Navigates to the trendingNowScreen when the action is triggered.
onTapTxtSeeAllText(BuildContext context) { NavigatorService.pushNamed(AppRoutes.trendingNowScreen, ); } 
/// Navigates to the popularArtistsScreen when the action is triggered.
onTapTxtSeeAllText1(BuildContext context) { NavigatorService.pushNamed(AppRoutes.popularArtistsScreen, ); } 
 }
