import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_elevated_button.dart';import 'bloc/playlist_details_one_bloc.dart';import 'models/playlist_details_one_model.dart';import 'models/playlistdetailslist_item_model.dart';import 'widgets/playlistdetailslist_item_widget.dart';class PlaylistDetailsOneScreen extends StatelessWidget {const PlaylistDetailsOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<PlaylistDetailsOneBloc>(create: (context) => PlaylistDetailsOneBloc(PlaylistDetailsOneState(playlistDetailsOneModelObj: PlaylistDetailsOneModel()))..add(PlaylistDetailsOneInitialEvent()), child: PlaylistDetailsOneScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgImage255x250, height: 256.v, width: 250.h, radius: BorderRadius.circular(28.h)), SizedBox(height: 19.v), Text("lbl_sweetener".tr, style: theme.textTheme.headlineLarge), SizedBox(height: 12.v), Text("lbl_ariana_grande".tr, style: CustomTextStyles.titleMediumPrimaryMedium), SizedBox(height: 15.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_playlist".tr, style: CustomTextStyles.titleSmallGray70001Medium)), Padding(padding: EdgeInsets.only(left: 12.h, top: 1.v), child: Text("lbl".tr, style: CustomTextStyles.titleSmallGray70001Medium)), Padding(padding: EdgeInsets.only(left: 12.h), child: Text("lbl_2022".tr, style: CustomTextStyles.titleSmallGray70001Medium))]), SizedBox(height: 12.v), _buildPlayRow(context), SizedBox(height: 23.v), Divider(), SizedBox(height: 25.v), _buildSongsRow(context), SizedBox(height: 21.v), _buildPlaylistDetailsList(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 11.v)), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 11.v))]); } 
/// Section Widget
Widget _buildPlayRow(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgFavorite, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v)), Spacer(flex: 18), CustomImageView(imagePath: ImageConstant.imgCategoriesPlaylist, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v)), Spacer(flex: 18), CustomImageView(imagePath: ImageConstant.imgLightBulb, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v)), Spacer(flex: 18), CustomImageView(imagePath: ImageConstant.imgCategoriesMore, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v)), Spacer(flex: 44), CustomElevatedButton(height: 45.v, width: 112.h, text: "lbl_play".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgCategoriesplayComponentadditionalIcons, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.fillPrimaryTL22, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700_1, onPressed: () {onTapPlay(context);})]); } 
/// Section Widget
Widget _buildSongsRow(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_songs".tr, style: theme.textTheme.headlineSmall), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 6.v), child: Text("lbl_see_all".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer16))]); } 
/// Section Widget
Widget _buildPlaylistDetailsList(BuildContext context) { return BlocSelector<PlaylistDetailsOneBloc, PlaylistDetailsOneState, PlaylistDetailsOneModel?>(selector: (state) => state.playlistDetailsOneModelObj, builder: (context, playlistDetailsOneModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: playlistDetailsOneModelObj?.playlistdetailslistItemList.length ?? 0, itemBuilder: (context, index) {PlaylistdetailslistItemModel model = playlistDetailsOneModelObj?.playlistdetailslistItemList[index] ?? PlaylistdetailslistItemModel(); return PlaylistdetailslistItemWidget(model, onTapSongCard: () {onTapSongCard(context);});});}); } 
/// Navigates to the songPlayScreen when the action is triggered.
onTapSongCard(BuildContext context) { NavigatorService.pushNamed(AppRoutes.songPlayScreen); } 
/// Navigates to the songPlayScreen when the action is triggered.
onTapPlay(BuildContext context) { NavigatorService.pushNamed(AppRoutes.songPlayScreen, ); } 
 }
