import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_title.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_elevated_button.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_outlined_button.dart';import 'bloc/select_payment_method_bloc.dart';import 'models/select_payment_method_model.dart';import 'models/selectpaymentmethod_item_model.dart';import 'widgets/selectpaymentmethod_item_widget.dart';class SelectPaymentMethodScreen extends StatelessWidget {const SelectPaymentMethodScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SelectPaymentMethodBloc>(create: (context) => SelectPaymentMethodBloc(SelectPaymentMethodState(selectPaymentMethodModelObj: SelectPaymentMethodModel()))..add(SelectPaymentMethodInitialEvent()), child: SelectPaymentMethodScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 29.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_select_the_payment".tr, style: CustomTextStyles.titleMediumPrimaryMedium16), SizedBox(height: 23.v), _buildSelectPaymentMethod(context), SizedBox(height: 30.v), CustomOutlinedButton(text: "lbl_add_new_card".tr, onPressed: () {onTapAddNewCard(context);}), SizedBox(height: 5.v)])), bottomNavigationBar: _buildContinueButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 14.v)), title: AppbarTitle(text: "lbl_payment".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgIconlyLightScan, margin: EdgeInsets.fromLTRB(24.h, 11.v, 24.h, 14.v))]); } 
/// Section Widget
Widget _buildSelectPaymentMethod(BuildContext context) { return BlocSelector<SelectPaymentMethodBloc, SelectPaymentMethodState, SelectPaymentMethodModel?>(selector: (state) => state.selectPaymentMethodModelObj, builder: (context, selectPaymentMethodModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: selectPaymentMethodModelObj?.selectpaymentmethodItemList.length ?? 0, itemBuilder: (context, index) {SelectpaymentmethodItemModel model = selectPaymentMethodModelObj?.selectpaymentmethodItemList[index] ?? SelectpaymentmethodItemModel(); return SelectpaymentmethodItemWidget(model);});}); } 
/// Section Widget
Widget _buildContinueButton(BuildContext context) { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 48.v), onPressed: () {onTapContinueButton(context);}); } 
/// Navigates to the addNewCardScreen when the action is triggered.
onTapAddNewCard(BuildContext context) { NavigatorService.pushNamed(AppRoutes.addNewCardScreen, ); } 
/// Navigates to the paymentSummaryScreen when the action is triggered.
onTapContinueButton(BuildContext context) { NavigatorService.pushNamed(AppRoutes.paymentSummaryScreen, ); } 
 }
