import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_title.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_elevated_button.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_outlined_button.dart';import 'bloc/downloads_bloc.dart';import 'models/downloads_item_model.dart';import 'models/downloads_model.dart';import 'widgets/downloads_item_widget.dart';class DownloadsScreen extends StatelessWidget {const DownloadsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<DownloadsBloc>(create: (context) => DownloadsBloc(DownloadsState(downloadsModelObj: DownloadsModel()))..add(DownloadsInitialEvent()), child: DownloadsScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 25.v), child: Column(children: [_buildSortBy(context), SizedBox(height: 22.v), Divider(), SizedBox(height: 23.v), _buildShuffle(context), SizedBox(height: 24.v), _buildDownloads(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 11.v)), title: AppbarTitle(text: "lbl_downloads".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.only(left: 24.h, top: 11.v, right: 11.h)), AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.only(left: 20.h, top: 11.v, right: 35.h))]); } 
/// Section Widget
Widget _buildSortBy(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_sort_by".tr, style: theme.textTheme.titleLarge), Spacer(), Text("msg_recently_downloaded".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer16), CustomImageView(imagePath: ImageConstant.imgIconlyCurvedSwap, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 12.h, bottom: 4.v))]); } 
/// Section Widget
Widget _buildShuffle(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomElevatedButton(text: "lbl_shuffle".tr, margin: EdgeInsets.only(right: 6.h), leftIcon: Container(margin: EdgeInsets.only(right: 16.h), child: CustomImageView(imagePath: ImageConstant.imgCategoriesshuffleComponentadditionalIcons, height: 20.adaptSize, width: 20.adaptSize)))), Expanded(child: CustomOutlinedButton(text: "lbl_play".tr, margin: EdgeInsets.only(left: 6.h), leftIcon: Container(margin: EdgeInsets.only(right: 16.h), child: CustomImageView(imagePath: ImageConstant.imgOverflowmenu, height: 20.adaptSize, width: 20.adaptSize))))]); } 
/// Section Widget
Widget _buildDownloads(BuildContext context) { return BlocSelector<DownloadsBloc, DownloadsState, DownloadsModel?>(selector: (state) => state.downloadsModelObj, builder: (context, downloadsModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: downloadsModelObj?.downloadsItemList.length ?? 0, itemBuilder: (context, index) {DownloadsItemModel model = downloadsModelObj?.downloadsItemList[index] ?? DownloadsItemModel(); return DownloadsItemWidget(model, onTapSongCard: () {onTapSongCard(context);});});}); } 
/// Navigates to the songPlayScreen when the action is triggered.
onTapSongCard(BuildContext context) { NavigatorService.pushNamed(AppRoutes.songPlayScreen); } 
 }
