import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_title.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'bloc/albums_bloc.dart';import 'models/albums_item_model.dart';import 'models/albums_model.dart';import 'widgets/albums_item_widget.dart';class AlbumsScreen extends StatelessWidget {const AlbumsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<AlbumsBloc>(create: (context) => AlbumsBloc(AlbumsState(albumsModelObj: AlbumsModel()))..add(AlbumsInitialEvent()), child: AlbumsScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 31.v), child: Column(children: [_buildAutoLayoutHorizontal(context), SizedBox(height: 22.v), Divider(), SizedBox(height: 23.v), _buildAlbums(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 11.v)), title: AppbarTitle(text: "lbl_albums".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.only(left: 24.h, top: 11.v, right: 11.h)), AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.only(left: 20.h, top: 11.v, right: 35.h))]); } 
/// Section Widget
Widget _buildAutoLayoutHorizontal(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("lbl_sort_by".tr, style: theme.textTheme.titleLarge), Spacer(), Text("lbl_recently_added".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer16), CustomImageView(imagePath: ImageConstant.imgIconlyCurvedSwap, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 12.h, bottom: 4.v))]); } 
/// Section Widget
Widget _buildAlbums(BuildContext context) { return BlocSelector<AlbumsBloc, AlbumsState, AlbumsModel?>(selector: (state) => state.albumsModelObj, builder: (context, albumsModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: albumsModelObj?.albumsItemList.length ?? 0, itemBuilder: (context, index) {AlbumsItemModel model = albumsModelObj?.albumsItemList[index] ?? AlbumsItemModel(); return AlbumsItemWidget(model);});}); } 
 }
