import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_title.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'bloc/podcasts_bloc.dart';import 'models/artistslist_item_model.dart';import 'models/explorepodcastsgrid_item_model.dart';import 'models/podcasts_model.dart';import 'models/popularpodcastslist_item_model.dart';import 'widgets/artistslist_item_widget.dart';import 'widgets/explorepodcastsgrid_item_widget.dart';import 'widgets/popularpodcastslist_item_widget.dart';class PodcastsScreen extends StatelessWidget {const PodcastsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<PodcastsBloc>(create: (context) => PodcastsBloc(PodcastsState(podcastsModelObj: PodcastsModel()))..add(PodcastsInitialEvent()), child: PodcastsScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 32.v), child: Column(children: [Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(context, popularArtistsText: "msg_popular_podcasts".tr, seeAllText: "lbl_see_all".tr)), SizedBox(height: 13.v), _buildPopularPodcastsList(context), SizedBox(height: 30.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(context, popularArtistsText: "lbl_popular_artists".tr, seeAllText: "lbl_see_all".tr)), SizedBox(height: 13.v), _buildArtistsList(context), SizedBox(height: 30.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildPopularArtistsRow(context, popularArtistsText: "lbl_categories".tr, seeAllText: "lbl_see_all".tr)), SizedBox(height: 13.v), _buildExplorePodcastsGrid(context)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 10.v, bottom: 10.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_podcasts".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.only(left: 24.h, top: 10.v, right: 10.h)), AppbarTrailingImage(imagePath: ImageConstant.imgTelevision, margin: EdgeInsets.only(left: 20.h, top: 10.v, right: 10.h)), AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.only(left: 20.h, top: 10.v, right: 34.h))]); } 
/// Section Widget
Widget _buildPopularPodcastsList(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 220.v, child: BlocSelector<PodcastsBloc, PodcastsState, PodcastsModel?>(selector: (state) => state.podcastsModelObj, builder: (context, podcastsModelObj) {return ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: podcastsModelObj?.popularpodcastslistItemList.length ?? 0, itemBuilder: (context, index) {PopularpodcastslistItemModel model = podcastsModelObj?.popularpodcastslistItemList[index] ?? PopularpodcastslistItemModel(); return PopularpodcastslistItemWidget(model);});}))); } 
/// Section Widget
Widget _buildArtistsList(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 209.v, child: BlocSelector<PodcastsBloc, PodcastsState, PodcastsModel?>(selector: (state) => state.podcastsModelObj, builder: (context, podcastsModelObj) {return ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: podcastsModelObj?.artistslistItemList.length ?? 0, itemBuilder: (context, index) {ArtistslistItemModel model = podcastsModelObj?.artistslistItemList[index] ?? ArtistslistItemModel(); return ArtistslistItemWidget(model);});}))); } 
/// Section Widget
Widget _buildExplorePodcastsGrid(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: BlocSelector<PodcastsBloc, PodcastsState, PodcastsModel?>(selector: (state) => state.podcastsModelObj, builder: (context, podcastsModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 121.v, crossAxisCount: 2, mainAxisSpacing: 12.h, crossAxisSpacing: 12.h), physics: NeverScrollableScrollPhysics(), itemCount: podcastsModelObj?.explorepodcastsgridItemList.length ?? 0, itemBuilder: (context, index) {ExplorepodcastsgridItemModel model = podcastsModelObj?.explorepodcastsgridItemList[index] ?? ExplorepodcastsgridItemModel(); return ExplorepodcastsgridItemWidget(model, onTapExploreCard: () {onTapExploreCard(context);});});})); } 
/// Common widget
Widget _buildPopularArtistsRow(BuildContext context, {required String popularArtistsText, required String seeAllText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(popularArtistsText, style: theme.textTheme.headlineSmall!.copyWith(color: appTheme.gray90001))), Padding(padding: EdgeInsets.only(bottom: 10.v), child: Text(seeAllText, style: CustomTextStyles.titleMediumOnPrimaryContainer16.copyWith(color: theme.colorScheme.onPrimaryContainer)))]); } 
/// Navigates to the newReleasesScreen when the action is triggered.
onTapExploreCard(BuildContext context) { NavigatorService.pushNamed(AppRoutes.newReleasesScreen); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
