import 'package:flutter/material.dart';import 'package:country_pickers/country.dart';import 'package:country_pickers/country_pickers.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/core/utils/validation_functions.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_title.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_drop_down.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_elevated_button.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_phone_number.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_text_form_field.dart';import 'bloc/edit_profile_bloc.dart';import 'models/edit_profile_model.dart';
// ignore_for_file: must_be_immutable
class EditProfileScreen extends StatelessWidget {EditProfileScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<EditProfileBloc>(create: (context) => EditProfileBloc(EditProfileState(editProfileModelObj: EditProfileModel()))..add(EditProfileInitialEvent()), child: EditProfileScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom), child: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 31.v), child: Column(children: [_buildInputFields1(context), SizedBox(height: 24.v), _buildInputFields2(context), SizedBox(height: 24.v), _buildDate(context), SizedBox(height: 24.v), _buildEmail(context), SizedBox(height: 24.v), _buildPhoneNumber(context), SizedBox(height: 24.v), BlocSelector<EditProfileBloc, EditProfileState, EditProfileModel?>(selector: (state) => state.editProfileModelObj, builder: (context, editProfileModelObj) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 20.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgIconBottom, height: 20.adaptSize, width: 20.adaptSize)), hintText: "lbl_male".tr, items: editProfileModelObj?.dropdownItemList ?? [], contentPadding: EdgeInsets.only(left: 20.h, top: 19.v, bottom: 19.v), borderDecoration: DropDownStyleHelper.fillGrayTL16, fillColor: appTheme.gray100, onChanged: (value) {context.read<EditProfileBloc>().add(ChangeDropDownEvent(value: value));});}), SizedBox(height: 5.v)]))))), bottomNavigationBar: _buildUpdate(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 9.v)), title: AppbarTitle(text: "lbl_edit_profile".tr, margin: EdgeInsets.only(left: 16.h))); } 
/// Section Widget
Widget _buildInputFields1(BuildContext context) { return BlocSelector<EditProfileBloc, EditProfileState, TextEditingController?>(selector: (state) => state.inputFields1Controller, builder: (context, inputFields1Controller) {return CustomTextFormField(controller: inputFields1Controller, hintText: "lbl_andrew_ainsley".tr);}); } 
/// Section Widget
Widget _buildInputFields2(BuildContext context) { return BlocSelector<EditProfileBloc, EditProfileState, TextEditingController?>(selector: (state) => state.inputFields2Controller, builder: (context, inputFields2Controller) {return CustomTextFormField(controller: inputFields2Controller, hintText: "lbl_andrew".tr);}); } 
/// Section Widget
Widget _buildDate(BuildContext context) { return BlocSelector<EditProfileBloc, EditProfileState, TextEditingController?>(selector: (state) => state.dateController, builder: (context, dateController) {return CustomTextFormField(controller: dateController, hintText: "lbl_27_12_1995".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 20.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgIconsPrimary, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 56.v), contentPadding: EdgeInsets.only(left: 20.h, top: 19.v, bottom: 19.v));}); } 
/// Section Widget
Widget _buildEmail(BuildContext context) { return BlocSelector<EditProfileBloc, EditProfileState, TextEditingController?>(selector: (state) => state.emailController, builder: (context, emailController) {return CustomTextFormField(controller: emailController, hintText: "lbl_user_domain_com".tr, textInputType: TextInputType.emailAddress, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 20.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgIconsPrimary20x20, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 56.v), validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}, contentPadding: EdgeInsets.only(left: 20.h, top: 19.v, bottom: 19.v));}); } 
/// Section Widget
Widget _buildPhoneNumber(BuildContext context) { return BlocBuilder<EditProfileBloc, EditProfileState>(builder: (context, state) {return CustomPhoneNumber(country: state.selectedCountry ?? CountryPickerUtils.getCountryByPhoneCode('1'), controller: state.phoneNumberController, onTap: (Country value) {context.read<EditProfileBloc>().add(ChangeCountryEvent(value: value));});}); } 
/// Section Widget
Widget _buildUpdate(BuildContext context) { return CustomElevatedButton(text: "lbl_update".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 48.v), onPressed: () {onTapUpdate(context);}); } 
/// Navigates to the profileDetailsOneScreen when the action is triggered.
onTapUpdate(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileDetailsOneScreen, ); } 
 }
