import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_title.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_elevated_button.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_pin_code_text_field.dart';import 'bloc/create_new_pin_bloc.dart';import 'models/create_new_pin_model.dart';class CreateNewPinScreen extends StatelessWidget {const CreateNewPinScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<CreateNewPinBloc>(create: (context) => CreateNewPinBloc(CreateNewPinState(createNewPinModelObj: CreateNewPinModel()))..add(CreateNewPinInitialEvent()), child: CreateNewPinScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 138.v), child: Column(children: [Container(width: 331.h, margin: EdgeInsets.symmetric(horizontal: 24.h), child: Text("msg_add_a_pin_number".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyLarge!.copyWith(height: 1.40))), SizedBox(height: 79.v), Padding(padding: EdgeInsets.only(right: 18.h), child: BlocSelector<CreateNewPinBloc, CreateNewPinState, TextEditingController?>(selector: (state) => state.otpController, builder: (context, otpController) {return CustomPinCodeTextField(context: context, controller: otpController, onChanged: (value) {otpController?.text = value;});})), Spacer(flex: 35), CustomElevatedButton(text: "lbl_continue".tr, onPressed: () {onTapContinue(context);}), Spacer(flex: 64)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 49.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 10.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_create_new_pin".tr, margin: EdgeInsets.only(left: 16.h))); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the setFingerprintScreen when the action is triggered.
onTapContinue(BuildContext context) { NavigatorService.pushNamed(AppRoutes.setFingerprintScreen, ); } 
 }
