import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_title.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'bloc/new_releases_bloc.dart';import 'models/new_releases_model.dart';import 'models/newreleasesgrid_item_model.dart';import 'models/newreleaseslist_item_model.dart';import 'widgets/newreleasesgrid_item_widget.dart';import 'widgets/newreleaseslist_item_widget.dart';class NewReleasesScreen extends StatelessWidget {const NewReleasesScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<NewReleasesBloc>(create: (context) => NewReleasesBloc(NewReleasesState(newReleasesModelObj: NewReleasesModel()))..add(NewReleasesInitialEvent()), child: NewReleasesScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 31.v), child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_the_best_new_releases".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 16.v), _buildNewReleasesList(context), SizedBox(height: 36.v), Text("msg_new_albums_single".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 13.v), _buildNewReleasesGrid(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 48.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 11.v, bottom: 9.v), onTap: () {onTapArrowDown(context);}), title: AppbarTitle(text: "lbl_new_releases".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewind, margin: EdgeInsets.fromLTRB(24.h, 11.v, 24.h, 9.v))]); } 
/// Section Widget
Widget _buildNewReleasesList(BuildContext context) { return SizedBox(height: 242.v, child: BlocSelector<NewReleasesBloc, NewReleasesState, NewReleasesModel?>(selector: (state) => state.newReleasesModelObj, builder: (context, newReleasesModelObj) {return ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: newReleasesModelObj?.newreleaseslistItemList.length ?? 0, itemBuilder: (context, index) {NewreleaseslistItemModel model = newReleasesModelObj?.newreleaseslistItemList[index] ?? NewreleaseslistItemModel(); return NewreleaseslistItemWidget(model);});})); } 
/// Section Widget
Widget _buildNewReleasesGrid(BuildContext context) { return BlocSelector<NewReleasesBloc, NewReleasesState, NewReleasesModel?>(selector: (state) => state.newReleasesModelObj, builder: (context, newReleasesModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 245.v, crossAxisCount: 2, mainAxisSpacing: 12.h, crossAxisSpacing: 12.h), physics: NeverScrollableScrollPhysics(), itemCount: newReleasesModelObj?.newreleasesgridItemList.length ?? 0, itemBuilder: (context, index) {NewreleasesgridItemModel model = newReleasesModelObj?.newreleasesgridItemList[index] ?? NewreleasesgridItemModel(); return NewreleasesgridItemWidget(model);});}); } 

/// Navigates to the previous screen.
onTapArrowDown(BuildContext context) { NavigatorService.goBack(); } 
 }
