import 'package:flutter/material.dart';import 'package:dhiwise_flutter_music_app/core/app_export.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_leading_image.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_title.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:dhiwise_flutter_music_app/widgets/app_bar/custom_app_bar.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_elevated_button.dart';import 'package:dhiwise_flutter_music_app/widgets/custom_switch.dart';import 'bloc/profile_settings_bloc.dart';import 'models/profile_settings_model.dart';class ProfileSettingsPage extends StatelessWidget {const ProfileSettingsPage({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ProfileSettingsBloc>(create: (context) => ProfileSettingsBloc(ProfileSettingsState(profileSettingsModelObj: ProfileSettingsModel()))..add(ProfileSettingsInitialEvent()), child: ProfileSettingsPage()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 30.v), child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [SizedBox(height: 80.adaptSize, width: 80.adaptSize, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgEllipse80x80, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(40.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgEdit, height: 20.adaptSize, width: 20.adaptSize, alignment: Alignment.bottomRight)])), Padding(padding: EdgeInsets.only(left: 20.h, top: 15.v, bottom: 15.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_andrew_ainsley".tr, style: theme.textTheme.titleLarge), SizedBox(height: 8.v), Text("lbl_user_domain_com".tr, style: theme.textTheme.titleSmall)]))]), SizedBox(height: 23.v), _buildGetPremium(context), SizedBox(height: 24.v), _buildSecurity(context, icon: ImageConstant.imgLock, title: "lbl_profile".tr, onTapSecurity: () {onTapSecurity(context);}), SizedBox(height: 24.v), _buildNotification(context), SizedBox(height: 24.v), _buildAudioVideo(context), SizedBox(height: 24.v), _buildPlayback(context), SizedBox(height: 24.v), _buildDataSaverStorage(context), SizedBox(height: 24.v), _buildSecurity(context, icon: ImageConstant.imgIconlyCurvedShield, title: "lbl_security".tr, onTapSecurity: () {onTapSecurity1(context);}), SizedBox(height: 24.v), _buildLanguage(context), SizedBox(height: 24.v), _buildDarkMode(context), SizedBox(height: 24.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgUserRedA200, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("lbl_logout".tr, style: CustomTextStyles.titleMediumRedA200))])])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 56.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgVector, margin: EdgeInsets.only(left: 24.h, top: 9.v, bottom: 9.v)), title: AppbarTitle(text: "lbl_profile".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgSettingsGray90001, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 11.v))]); } 
/// Section Widget
Widget _buildGetPremium(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 23.h), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder32), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 30.v, bottom: 27.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_enjoy_all_benefits".tr, style: CustomTextStyles.headlineSmallWhiteA700), SizedBox(height: 8.v), SizedBox(width: 202.h, child: Text("msg_enjoy_listening".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall)), SizedBox(height: 11.v), CustomElevatedButton(height: 32.v, width: 116.h, text: "lbl_get_premium".tr, buttonStyle: CustomButtonStyles.fillWhiteA, buttonTextStyle: CustomTextStyles.titleSmallOnPrimaryContainer, onPressed: () {onTapGetPremium(context);})])), CustomImageView(imagePath: ImageConstant.imgMusicFococlippingStandard, height: 169.v, width: 115.h, margin: EdgeInsets.only(top: 13.v))])); } 
/// Section Widget
Widget _buildNotification(BuildContext context) { return GestureDetector(onTap: () {onTapNotification(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 144.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconsGray90001, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Text("lbl_notification".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildAudioVideo(BuildContext context) { return GestureDetector(onTap: () {onTapAudioVideo(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgMenu, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 2.v, bottom: 3.v), child: Text("lbl_audio_video".tr, style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildPlayback(BuildContext context) { return GestureDetector(onTap: () {onTapPlayback(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 124.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedPlay, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 5.v), child: Text("lbl_playback".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildDataSaverStorage(BuildContext context) { return GestureDetector(onTap: () {onTapDataSaverStorage(context);}, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedTick, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("msg_data_saver_storage".tr, style: CustomTextStyles.titleMediumSemiBold_1))]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Section Widget
Widget _buildLanguage(BuildContext context) { return GestureDetector(onTap: () {onTapLanguage(context);}, child: Row(children: [CustomImageView(imagePath: ImageConstant.imgIconlyCurvedMore, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text("lbl_language".tr, style: CustomTextStyles.titleMediumSemiBold_1)), Spacer(), Padding(padding: EdgeInsets.only(top: 5.v), child: Text("lbl_english_us".tr, style: CustomTextStyles.titleMediumSemiBold_1)), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 20.h, top: 4.v, bottom: 4.v))])); } 
/// Section Widget
Widget _buildDarkMode(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(width: 139.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgEyeGray90001, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Text("lbl_dark_mode".tr, style: CustomTextStyles.titleMediumSemiBold_1))])), BlocSelector<ProfileSettingsBloc, ProfileSettingsState, bool?>(selector: (state) => state.isSelectedSwitch, builder: (context, isSelectedSwitch) {return CustomSwitch(value: isSelectedSwitch, onChange: (value) {context.read<ProfileSettingsBloc>().add(ChangeSwitchEvent(value: value));});})]); } 
/// Common widget
Widget _buildSecurity(BuildContext context, {required String icon, required String title, Function? onTapSecurity, }) { return GestureDetector(onTap: () {onTapSecurity!.call();}, child: Row(children: [CustomImageView(imagePath: icon, height: 28.adaptSize, width: 28.adaptSize), Padding(padding: EdgeInsets.only(left: 20.h, top: 5.v), child: Text(title, style: CustomTextStyles.titleMediumSemiBold_1.copyWith(color: appTheme.gray90001))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v))])); } 
/// Navigates to the subscribeScreen when the action is triggered.
onTapGetPremium(BuildContext context) { NavigatorService.pushNamed(AppRoutes.subscribeScreen, ); } 
/// Navigates to the profileDetailsOneScreen when the action is triggered.
onTapSecurity(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileDetailsOneScreen, ); } 
/// Navigates to the notificationSettingsScreen when the action is triggered.
onTapNotification(BuildContext context) { NavigatorService.pushNamed(AppRoutes.notificationSettingsScreen, ); } 
/// Navigates to the audioVideoScreen when the action is triggered.
onTapAudioVideo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.audioVideoScreen, ); } 
/// Navigates to the playbackScreen when the action is triggered.
onTapPlayback(BuildContext context) { NavigatorService.pushNamed(AppRoutes.playbackScreen, ); } 
/// Navigates to the dataSaverStorageScreen when the action is triggered.
onTapDataSaverStorage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.dataSaverStorageScreen, ); } 
/// Navigates to the securityScreen when the action is triggered.
onTapSecurity1(BuildContext context) { NavigatorService.pushNamed(AppRoutes.securityScreen, ); } 
/// Navigates to the languageScreen when the action is triggered.
onTapLanguage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.languageScreen, ); } 
 }
